/aruco_node:
  ros__parameters:
    marker_size: 0.187
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /l515_right_camera/color/image_unclipped_raw
    camera_info_topic: /l515_right_camera/color/camera_info
