/aruco_node:
  ros__parameters:
    marker_size: 0.287
    aruco_dictionary_id: DICT_7X7_1000
    image_topic: /l515_right_camera/color/image_unclipped_raw
    camera_info_topic: /l515_right_camera/color/camera_info
    camera_frame: l515_right_camera_color_optical_frame_gl
